In [16]:
import pandas as pd
df = pd.read_csv('./CosmoAstroSeed_IllustrisTNG.txt', sep='\s+')
df

       Name  Omega_m  sigma_8      A_SN1     A_AGN1    A_SN2   A_AGN2   seed
0      LH_0   0.3090   0.9790    3.11234    1.12194  0.66850  0.53182      0
1      LH_1   0.3026   0.9394    3.42001    3.96137  1.03311  1.16070      1
2      LH_2   0.4282   0.7530    0.70613    0.37423  1.96292  0.62720      2
3      LH_3   0.1906   0.6286    1.60882    0.39887  0.86634  0.86634      3
4      LH_4   0.1382   0.6874    1.19914    0.27586  0.82188  0.91700      4
...     ...      ...      ...        ...        ...      ...      ...    ...
1092  CV_26   0.3000   0.8000    1.00000    1.00000  1.00000  1.00000     27
1093   EX_0   0.3000   0.8000    1.00000    1.00000  1.00000  1.00000  13560
1094   EX_1   0.3000   0.8000    1.00000  100.00000  1.00000  1.00000  13560
1095   EX_2   0.3000   0.8000  100.00000    1.00000  1.00000  1.00000  13560
1096   EX_3   0.3000   0.8000    0.00000    0.00000  0.00000  0.00000  13560

[1097 rows x 8 columns]

In [10]:
sequence = []
for i in range(1, 7):
    for j in range(-5, 6):
        n = f'n{abs(j)}' if j < 0 else f'{j}'
        sequence += [f'1P_{i}_{n}']
        
sequence

['1P_1_n5',
 '1P_1_n4',
 '1P_1_n3',
 '1P_1_n2',
 '1P_1_n1',
 '1P_1_0',
 '1P_1_1',
 '1P_1_2',
 '1P_1_3',
 '1P_1_4',
 '1P_1_5',
 '1P_2_n5',
 '1P_2_n4',
 '1P_2_n3',
 '1P_2_n2',
 '1P_2_n1',
 '1P_2_0',
 '1P_2_1',
 '1P_2_2',
 '1P_2_3',
 '1P_2_4',
 '1P_2_5',
 '1P_3_n5',
 '1P_3_n4',
 '1P_3_n3',
 '1P_3_n2',
 '1P_3_n1',
 '1P_3_0',
 '1P_3_1',
 '1P_3_2',
 '1P_3_3',
 '1P_3_4',
 '1P_3_5',
 '1P_4_n5',
 '1P_4_n4',
 '1P_4_n3',
 '1P_4_n2',
 '1P_4_n1',
 '1P_4_0',
 '1P_4_1',
 '1P_4_2',
 '1P_4_3',
 '1P_4_4',
 '1P_4_5',
 '1P_5_n5',
 '1P_5_n4',
 '1P_5_n3',
 '1P_5_n2',
 '1P_5_n1',
 '1P_5_0',
 '1P_5_1',
 '1P_5_2',
 '1P_5_3',
 '1P_5_4',
 '1P_5_5',
 '1P_6_n5',
 '1P_6_n4',
 '1P_6_n3',
 '1P_6_n2',
 '1P_6_n1',
 '1P_6_0',
 '1P_6_1',
 '1P_6_2',
 '1P_6_3',
 '1P_6_4',
 '1P_6_5']

In [31]:
df.loc[df["Name"].str.startswith("1P_"), "Name"] = sequence

In [32]:
df[df["Name"].str.startswith("1P_")]

         Name  Omega_m  sigma_8  A_SN1  A_AGN1  A_SN2   A_AGN2  seed
1000  1P_1_n5     0.10      0.8    1.0     1.0    1.0  1.00000    67
1001  1P_1_n4     0.14      0.8    1.0     1.0    1.0  1.00000    67
1002  1P_1_n3     0.18      0.8    1.0     1.0    1.0  1.00000    67
1003  1P_1_n2     0.22      0.8    1.0     1.0    1.0  1.00000    67
1004  1P_1_n1     0.26      0.8    1.0     1.0    1.0  1.00000    67
...       ...      ...      ...    ...     ...    ...      ...   ...
1061   1P_6_1     0.30      0.8    1.0     1.0    1.0  1.14870    67
1062   1P_6_2     0.30      0.8    1.0     1.0    1.0  1.31951    67
1063   1P_6_3     0.30      0.8    1.0     1.0    1.0  1.51572    67
1064   1P_6_4     0.30      0.8    1.0     1.0    1.0  1.74110    67
1065   1P_6_5     0.30      0.8    1.0     1.0    1.0  2.00000    67

[66 rows x 8 columns]

In [33]:
df.to_csv('camels_parameters.csv', index=False, float_format='%.5f')

In [36]:
df1 = pd.read_csv('./CosmoAstroSeed_IllustrisTNG.txt', sep='\s+')
df2 = pd.read_csv('./camels_parameters.csv')

df1.compare(df2)

       Name
       self    other
1000   1P_0  1P_1_n5
1001   1P_1  1P_1_n4
1002   1P_2  1P_1_n3
1003   1P_3  1P_1_n2
1004   1P_4  1P_1_n1
...     ...      ...
1061  1P_61   1P_6_1
1062  1P_62   1P_6_2
1063  1P_63   1P_6_3
1064  1P_64   1P_6_4
1065  1P_65   1P_6_5

[66 rows x 2 columns]